### PR TITLE
Create separate debian package for our custom version

### PR DESCRIPTION
**Pull request by ermshiperete**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/icu4c/17)

### CODE REVIEW

**Comment by StephenMcConnel** [comment]
This looks incomplete to me, but maybe I don't understand everything about debian packaging.  (There's really no "maybe" about it.)

---

Reviewed 2 of 9 files at r1.
Review status: 2 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[Jenkinsfile, line 133 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHAVHuocurUq7cp31h:-KkHAVHuocurUq7cp31i:b5254p4) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/Jenkinsfile#L133)):*
> ```Groovy
> 		}
> 	}
> }
> ```

I pretty much have to assume this file is okay, but I did scan over it without noticing any glaring problems.  Is having it here an alternative to being another jenkins specific repository?

---

*[debian/control, line 11 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkH9IZAzVqALWxZWYDQ:-KkH9IZBaVdvonVEIVdJ:b-ux87ce) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/control#L11)):*
> ```
> Build-Depends: debhelper (>= 9.0.0), dpkg-dev (>= 1.16.1~),
> 	autotools-dev,
> 	g++
> ```

does it depend on a minimum version of g++?  (or of autotools-dev?)

---

*[debian/control, line 45 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHA3qkXGreEhGeI1j8:-KkHA3qkXGreEhGeI1j9:b-tcdjhy) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/control#L45)):*
> ```
>  Unicode and locale support. This package contains FieldWorks specific
>  versions of the programs used to manipulate data files found in the ICU
>  sources.
> ```

How do the separate packages get built?  It seems like we're missing some files here to specify the content of the three binary packages.  Or do I just not understand packaging automation subtleties well enough?  (which is quite possible)

---

*[debian/copyright, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkH9atrP7iC57_Jx-JH:-KkH9atrP7iC57_Jx-JI:bbonsyo) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/copyright#L1)):*
> ```
> Packaging for FieldWorks by Eberhard Beilharz <eb1@sil.org> on May 16, 2017.
> ```

Isn't the copyright file supposed to be in a standard debian format?  That's how I would interpret https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/.

---

*[debian/docs, line 0 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHAsY4ZxLWxGl2C9cw:-KkHAsY5dQjISF3txy94:b-zgaa3z) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/docs#L0)):*
Do we really need this file if it's empty?

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-:-KkHB70NJxNBcvvkWYPB:b88nvtp)*

**Comment by StephenMcConnel** [comment]
Reviewed 4 of 9 files at r1.
Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17)*

**Comment by ermshiperete** [comment]
Yes, it is incomplete. Should have marked as WIP.

---

Review status: 6 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[Jenkinsfile, line 133 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHAVHuocurUq7cp31h:-KkJ77AdcDzbsZFEOB8T:b-qxdj99) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/Jenkinsfile#L133)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I pretty much have to assume this file is okay, but I did scan over it without noticing any glaring problems.  Is having it here an alternative to being another jenkins specific repository?
</blockquote></details>

yes, this `Jenkinsfile` replaces the job configuration for this branch in `ci-builder-scripts`. There is a general job set up for icu4c that scans the branches, and if it finds a branch with a `Jenkinsfile` it'll create a build job (https://jenkins.lsdev.sil.org:45192/view/Icu/view/All/job/icu4c/). Same thing could be done for all repos under github.com/sillsdev, but for now I decided to limit it to icu4c.

---

*[debian/control, line 11 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkH9IZAzVqALWxZWYDQ:-KkJ7wxr9BUA-OtRcIr-:bvxej5c) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/control#L11)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

does it depend on a minimum version of g++?  (or of autotools-dev?)
</blockquote></details>

The autotools line comes from the debian control file. For g++ there is probably a minimum version, but since all Ubuntu versions we support come with g++ versions that are sufficient and the Debian control files have different values it seemed easiest to simply not specify a minimum version.

---

*[debian/control, line 45 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHA3qkXGreEhGeI1j8:-KkJ8_ymMJUWFXWEMhpb:b7v76qt) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/control#L45)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

How do the separate packages get built?  It seems like we're missing some files here to specify the content of the three binary packages.  Or do I just not understand packaging automation subtleties well enough?  (which is quite possible)
</blockquote></details>

You are correct. There are some files missing. WIP.

---

*[debian/copyright, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkH9atrP7iC57_Jx-JH:-KkJ8hHqNSCvV8zG8Mq4:bwdhipw) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/copyright#L1)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Isn't the copyright file supposed to be in a standard debian format?  That's how I would interpret https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/.
</blockquote></details>

Yes, would probably be better to have it in the standard format. But I simply copied the copyright file from the Debian package and slightly modified it.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-:-KkJ6wGYOFzbYQSZbXat:b-x6y744)*

**Comment by ermshiperete** [comment]
Review status: 4 of 9 files reviewed at latest revision, 5 unresolved discussions.

---

*[debian/copyright, line 1 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkH9atrP7iC57_Jx-JH:-KkK0VVgpbVKSdVToMfd:b-34g5mh) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/copyright#L1)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

Yes, would probably be better to have it in the standard format. But I simply copied the copyright file from the Debian package and slightly modified it.
</blockquote></details>

Honestly, I don't know which files have which copyright and it doesn't seem worth the effort to figure that out since this is a specialized package used (and useful) only by FW.

---

*[debian/docs, line  at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHAsY4ZxLWxGl2C9cw:-KkK0rMG1nJMhG7RUTw2:bc33ndm) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/docs#L)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

Do we really need this file if it's empty?
</blockquote></details>

I'm trying a build without.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17)*

**Comment by ermshiperete** [comment]
I think this is now ready :smile: 

---

Review status: 4 of 8 files reviewed at latest revision, 5 unresolved discussions.

---

*[debian/docs, line  at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHAsY4ZxLWxGl2C9cw:-KkKjWLqp-YdHOQ-haH4:b-qajgz6) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/docs#L)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

I'm trying a build without.
</blockquote></details>

yep, works without the empty `docs` file. Done.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-:-KkKjbgDZc_IYzc0vkbQ:blm467t)*

**Comment by StephenMcConnel** [comment]
Reviewed 1 of 4 files at r2.
Review status: 5 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[debian/control, line 45 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHA3qkXGreEhGeI1j8:-KkMpdrdIdceirFYT5Cf:b-xi0vyn) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/control#L45)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

You are correct. There are some files missing. WIP.
</blockquote></details>

I don't see any additional files yet, so I assume it's still WIP.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17)*

**Comment by StephenMcConnel** [comment]
Reviewed 1 of 9 files at r1, 1 of 4 files at r2.
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17)*

**Comment by ermshiperete** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[debian/control, line 45 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHA3qkXGreEhGeI1j8:-KkNd6Ai0MrPXI5Ndpc5:b49rpvf) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/control#L45)):*
<details><summary><i>Previously, StephenMcConnel (Steve McConnel) wrote…</i></summary><blockquote>

I don't see any additional files yet, so I assume it's still WIP.
</blockquote></details>

No, it's no longer WIP. The `rules` file distributes the files to the different binary package file locations.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17)*

**Comment by ermshiperete** [comment]
Review status: 6 of 8 files reviewed at latest revision, 1 unresolved discussion.

---

*[debian/control, line 45 at r1](https://reviewable.io:443/reviews/sillsdev/icu4c/17#-KkHA3qkXGreEhGeI1j8:-KkNdV4n-OmwjyR3anwU:bxzm6z1) ([raw file](https://github.com/sillsdev/icu4c/blob/cfabc2bc1e7dd729bcc9915fa40af9339908a0f2/debian/control#L45)):*
<details><summary><i>Previously, ermshiperete (Eberhard Beilharz) wrote…</i></summary><blockquote>

No, it's no longer WIP. The `rules` file distributes the files to the different binary package file locations.
</blockquote></details>

...seemed to be easier to just do it in the `rules` file rather than creating several `*.install` files.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sillsdev/icu4c/17)*

**Pull request merged**
